version: '3'
services:
  lx-mongo:
    image: mongo:3.2-jessie
    restart: always
    environment:
      MONGO_INITDB_DATABASE: luigi
  lx-luigid:
    build: .
    ports:
      - 127.0.0.1:8082:8082
    volumes:
      - ./project:/opt/project
    command: bash -c "pipenv sync && bash server.sh"
  lx-project:
    build: .
    volumes:
      - ./project:/opt/project
    command: bash -c "pipenv sync && bash client.sh"
    depends_on:
      - lx-mongo
      - lx-luigid
