[core]
logging_conf_file = "logging.conf"
default-scheduler-host = "lx-luigid"

[mongo]
host = "lx-mongo"
port = 27017
index = "luigi"
collection = "hello_world"

[retcode]
already_running = 10
missing_data = 20
not_run = 25
task_failed = 30
scheduling_error = 35
unhandled_exception = 40
